import type { I18NConfig } from "next/dist/server/config-shared.js";
import { existsSync, mkdirSync, writeFileSync } from "fs";
import { join, parse } from "path";
import { findFiles, getAppDirectory, getPagesDirectory } from "./utils.js";
import { version } from "./version.js";

type QueryType = "dynamic" | "catch-all" | "optional-catch-all";

interface Route {
  pathname: string;
  query: Record<string, QueryType>;
}

function convertWindowsPathToUnix(file: string): string {
  return file.replace(/\\/g, "/");
}

export function nextRoutes(pathnames: string[]): Route[] {
  const DYNAMIC_SEGMENT_RE = /\[(.*?)\]/g;

  return pathnames.map((pathname) => {
    const segments: string[] = pathname.match(DYNAMIC_SEGMENT_RE) ?? [];
    const query = segments.reduce<Route["query"]>((acc, cur) => {
      const param = cur
        .replace(/\[/g, "")
        .replace(/\]/g, "")
        .replace("...", "");
      let queryType: QueryType;
      if (cur.startsWith("[[...")) {
        queryType = "optional-catch-all";
      } else if (cur.startsWith("[...")) {
        queryType = "catch-all";
      } else {
        queryType = "dynamic";
      }
      acc[param] = queryType;
      return acc;
    }, {});

    return {
      pathname,
      query,
    };
  });
}

function getQueryInterface(
  query: Route["query"],
): [query: string, requiredKeys: number, optionalCatchAll: boolean] {
  let requiredKeys = 0;
  let optionalCatchAll = false;
  const keys = Object.entries(query)
    .map(([key, value]) => {
      switch (value) {
        case "dynamic": {
          requiredKeys += 1;
          return `"${key}": string`;
        }
        case "catch-all": {
          requiredKeys += 1;
          return `"${key}": string[]`;
        }
        case "optional-catch-all": {
          optionalCatchAll = true;
          return `"${key}"?: string[] | undefined`;
        }
        // istanbul ignore next: exhaustive typecheck
        default: {
          const _exhaust: never = value;
          return _exhaust;
        }
      }
    })
    .join("; ");

  return [`{ ${keys} }`, requiredKeys, optionalCatchAll];
}

interface GenerateConfig extends NextJSRoutesOptions {
  usingAppDirectory: boolean;
  usingPagesDirectory: boolean;
}

function generate(routes: Route[], config: GenerateConfig): string {
  const i18n = config.i18n ?? {
    defaultLocale: "",
    domains: [],
    localeDetection: false,
    locales: [],
  };
  let output = `\
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// This file will be automatically regenerated when your Next.js server is running.
// nextjs-routes version: ${version}
/* eslint-disable */

// prettier-ignore
declare module "nextjs-routes" {
  import type {
    GetServerSidePropsContext as NextGetServerSidePropsContext,
    GetServerSidePropsResult as NextGetServerSidePropsResult
  } from "next";

  export type Route =
    ${
      !routes.length
        ? "never"
        : `| ${routes
            .sort((a, b) => a.pathname.localeCompare(b.pathname))
            .map((route) => {
              const [params, requiredKeys, optionalCatchAll] =
                getQueryInterface(route.query);
              return requiredKeys > 0 || optionalCatchAll
                ? `DynamicRoute<"${route.pathname}", ${params}>`
                : `StaticRoute<"${route.pathname}">`;
            })
            .join("\n    | ")}`
    };

  interface StaticRoute<Pathname> {
    pathname: Pathname;
    query?: Query | undefined;
    hash?: string | null | undefined;
  }

  interface DynamicRoute<Pathname, Parameters> {
    pathname: Pathname;
    query: Parameters & Query;
    hash?: string | null | undefined;
  }

  interface Query {
    [key: string]: string | string[] | undefined;
  };

  export type RoutedQuery<P extends Route["pathname"] = Route["pathname"]> = Extract<
    Route,
    { pathname: P }
  >["query"];

  export type Locale = ${
    !i18n.locales.length
      ? "undefined"
      : `\n    | ${i18n.locales.map((x) => `"${x}"`).join("\n    | ")}`
  };

  type Brand<K, T> = K & { __brand: T };

  /**
   * A string that is a valid application route.
   */
  export type RouteLiteral = Brand<string, "RouteLiteral">

  /**
   * A typesafe utility function for generating paths in your application.
   *
   * route({ pathname: "/foos/[foo]", query: { foo: "bar" }}) will produce "/foos/bar".
   */
  export declare function route(r: Route): RouteLiteral;

  /**
   * Nearly identical to GetServerSidePropsContext from next, but further narrows
   * types based on nextjs-route's route data.
   */
  export type GetServerSidePropsContext<
    Pathname extends Route["pathname"] = Route["pathname"],
    Preview extends NextGetServerSidePropsContext["previewData"] = NextGetServerSidePropsContext["previewData"]
  > = Omit<NextGetServerSidePropsContext, 'params' | 'query' | 'defaultLocale' | 'locale' | 'locales'> & {
    params: Extract<Route, { pathname: Pathname }>["query"];
    query: Query;
    defaultLocale${
      i18n.defaultLocale ? `: "${i18n.defaultLocale}"` : "?: undefined"
    };
    locale${!i18n.locales.length ? "?:" : ":"} Locale;
    locales${
      i18n.locales.length ? `: ${print(i18n.locales, 8)}` : "?: undefined"
    };
  };

  /**
   * Nearly identical to GetServerSideProps from next, but further narrows
   * types based on nextjs-route's route data.
   */
  export type GetServerSideProps<
    Props extends { [key: string]: any } = { [key: string]: any },
    Pathname extends Route["pathname"] = Route["pathname"],
    Preview extends NextGetServerSideProps["previewData"] = NextGetServerSideProps["previewData"]
  > = (
    context: GetServerSidePropsContext<Pathname, Preview>
  ) => Promise<NextGetServerSidePropsResult<Props>>
}

// prettier-ignore
declare module "next/link" {
  ${(() => {
    if (config.usingAppDirectory) {
      return 'import type { Route, RouteLiteral } from "nextjs-routes";';
    } else {
      return 'import type { Route } from "nextjs-routes";';
    }
  })()};
  import type { LinkProps as NextLinkProps } from "next/dist/client/link";
  import type React from "react";

  type StaticRoute = Exclude<Route, { query: any }>["pathname"];

  export type LinkProps = Omit<NextLinkProps, "href" | "locale"> & {
    href: ${(() => {
      if (config.usingPagesDirectory && config.usingAppDirectory) {
        return 'Route | StaticRoute | Omit<Route, "pathname"> | RouteLiteral';
      } else if (config.usingPagesDirectory) {
        return 'Route | StaticRoute | Omit<Route, "pathname">';
      } else {
        return "StaticRoute | RouteLiteral";
      }
    })()};
    locale?: ${!i18n.locales.length ? "false" : `Locale | false`};
  }

  /**
   * A React component that extends the HTML \`<a>\` element to provide [prefetching](https://nextjs.org/docs/app/building-your-application/routing/linking-and-navigating#2-prefetching)
   * and client-side navigation between routes.
   *
   * It is the primary way to navigate between routes in Next.js.
   *
   * Read more: [Next.js docs: \`<Link>\`](https://nextjs.org/docs/app/api-reference/components/link)
   */
  declare const Link: React.ForwardRefExoticComponent<Omit<React.AnchorHTMLAttributes<HTMLAnchorElement>, keyof LinkProps> & LinkProps & {
      children?: React.ReactNode;
  } & React.RefAttributes<HTMLAnchorElement>>;
  export default Link;
}

// prettier-ignore
declare module "next/router" {
  import type { Locale, Route, RoutedQuery } from "nextjs-routes";
  import type { NextRouter as Router } from "next/dist/client/router";
  export * from "next/dist/client/router";
  export { default } from "next/dist/client/router";

  type NextTransitionOptions = NonNullable<Parameters<Router["push"]>[2]>;
  type StaticRoute = Exclude<Route, { query: any }>["pathname"];

  interface TransitionOptions extends Omit<NextTransitionOptions, "locale"> {
    locale?: ${!i18n.locales.length ? "false" : `Locale | false`};
  }

  type PathnameAndQuery<Pathname> = Required<
    Pick<Extract<Route, { pathname: Pathname }>, "pathname" | "query">
  >;

  type AutomaticStaticOptimizedQuery<PaQ> = Omit<PaQ, "query"> & {
    query: Partial<PaQ["query"]>;
  };

  type BaseRouter<PaQ> =
    | ({ isReady: false } & AutomaticStaticOptimizedQuery<PaQ>)
    | ({ isReady: true } & PaQ);

  export type NextRouter<P extends Route["pathname"] = Route["pathname"]> =
    BaseRouter<PathnameAndQuery<P>> &
      Omit<
        Router,
        | "defaultLocale"
        | "domainLocales"
        | "isReady"
        | "locale"
        | "locales"
        | "pathname"
        | "push"
        | "query"
        | "replace"
        | "route"
      > & {
        defaultLocale${
          i18n.defaultLocale ? `: "${i18n.defaultLocale}"` : "?: undefined"
        };
        domainLocales${
          i18n.domains?.length ? `: ${print(i18n.domains, 8)}` : "?: undefined"
        };
        locale${!i18n.locales.length ? "?:" : ":"} Locale;
        locales${
          i18n.locales.length ? `: ${print(i18n.locales, 8)}` : "?: undefined"
        };
        push(
          url: Route | StaticRoute | Omit<Route, "pathname">,
          as?: string,
          options?: TransitionOptions
        ): Promise<boolean>;
        replace(
          url: Route | StaticRoute | Omit<Route, "pathname">,
          as?: string,
          options?: TransitionOptions
        ): Promise<boolean>;
        route: P;
      };

  export function useRouter<P extends Route["pathname"]>(): NextRouter<P>;
}
`;

  if (config.usingAppDirectory) {
    output += `\

// prettier-ignore
declare module "next/navigation" {
  export * from "next/dist/client/components/navigation";
  import type { Route, RouteLiteral, RoutedQuery } from "nextjs-routes";
  import type { AppRouterInstance as NextAppRouterInstance, NavigateOptions, PrefetchOptions } from "next/dist/shared/lib/app-router-context.shared-runtime";

  type StaticRoute = Exclude<Route, { query: any }>["pathname"];

  /**
   * A [Client Component](https://nextjs.org/docs/app/building-your-application/rendering/client-components) hook
   * that lets you read the current URL's pathname.
   *
   * @example
   * \`\`\`ts
   * "use client"
   * import { usePathname } from 'next/navigation'
   *
   * export default function Page() {
   *  const pathname = usePathname() // returns "/dashboard" on /dashboard?foo=bar
   *  // ...
   * }
   * \`\`\`
   *
   * Read more: [Next.js Docs: \`usePathname\`](https://nextjs.org/docs/app/api-reference/functions/use-pathname)
   */
  export const usePathname: () => RouteLiteral;

  type AppRouterInstance = Omit<NextAppRouterInstance, 'push' | 'replace' | 'href'> & {
    push(href: StaticRoute | RouteLiteral, options?: NavigateOptions): void;
    replace(href: StaticRoute | RouteLiteral, options?: NavigateOptions): void;
    prefetch(href: StaticRoute | RouteLiteral, options?: PrefetchOptions): void;
  }

  /**
   *
   * This hook allows you to programmatically change routes inside [Client Component](https://nextjs.org/docs/app/building-your-application/rendering/client-components).
   *
   * @example
   * \`\`\`ts
   * "use client"
   * import { useRouter } from 'next/navigation'
   *
   * export default function Page() {
   *  const router = useRouter()
   *  // ...
   *  router.push('/dashboard') // Navigate to /dashboard
   * }
   * \`\`\`
   *
   * Read more: [Next.js Docs: \`useRouter\`](https://nextjs.org/docs/app/api-reference/functions/use-router)
   */
  export function useRouter(): AppRouterInstance;

  /**
   * A [Client Component](https://nextjs.org/docs/app/building-your-application/rendering/client-components) hook
   * that lets you read a route's dynamic params filled in by the current URL.
   *
   * @example
   * \`\`\`ts
   * "use client"
   * import { useParams } from 'next/navigation'
   *
   * export default function Page() {
   *   // on /dashboard/[team] where pathname is /dashboard/nextjs
   *   const { team } = useParams() // team === "nextjs"
   * }
   * \`\`\`
   *
   * Read more: [Next.js Docs: \`useParams\`](https://nextjs.org/docs/app/api-reference/functions/use-params)
   */
  export const useParams: <Pathname extends Route["pathname"] = Route["pathname"]>() => RoutedQuery<Pathname>;
}
`;
  }
  return output;
}

function print(x: unknown, indent: number): string {
  return JSON.stringify(x, undefined, 2)
    .split("\n")
    .join("\n" + " ".repeat(indent));
}

export interface NextJSRoutesOptions {
  /**
   * Location of the Next.js project. Defaults to the current working directory.
   *
   * This is only necessary when working with a non standard NextJS project setup, such as Nx.
   *
   * Example:
   *
   * // next.config.js
   * const nextRoutes = require("nextjs-routes/config")
   * const withRoutes = nextRoutes({ dir: __dirname });
   */
  dir?: string | undefined;
  /**
   * The file path indicating the output directory where the generated route types
   * should be written to (e.g.: "types").
   */
  outDir?: string | undefined;
  /**
   * NextJS config option.
   * https://nextjs.org/docs/api-reference/next.config.js/custom-page-extensions
   */
  pageExtensions?: string[] | undefined;
  /**
   * Internationalization configuration
   *
   * @see [Internationalization docs](https://nextjs.org/docs/advanced-features/i18n-routing)
   */
  i18n?: I18NConfig | null | undefined;
}

interface Opts {
  pageExtensions: string[];
  directory: string;
}

function commonProcessing(paths: string[], opts: Opts): string[] {
  return (
    paths
      // filter page extensions
      .filter((file) => {
        return opts.pageExtensions.some((ext) => file.endsWith(ext));
      })
      // remove file extensions (.tsx, .test.tsx)
      .map((file) => file.replace(/(\.\w+)+$/, ""))
      // remove duplicates from file extension removal (eg foo.ts and foo.test.ts)
      .filter((file, idx, array) => array.indexOf(file) === idx)
      // remove page directory path
      .map((file) => file.replace(opts.directory, ""))
      // normalize paths from windows users
      .map(convertWindowsPathToUnix)
  );
}

const APP_DIRECTORY_ROUTABLE_DIRECTORIES = ["page", "route"];

const APP_INTERCEPTING_ROUTE = ["(.)", "(..)", "(..)(..)", "(...)"];

function appDirectoryRoutable(file: string): boolean {
  const name = parse(file).name;
  return (
    // only consider page and route
    APP_DIRECTORY_ROUTABLE_DIRECTORIES.includes(name) &&
    // remove any filepaths that contain intercepts
    !APP_INTERCEPTING_ROUTE.some((intercept) => file.includes(intercept))
  );
}

export function getAppRoutes(files: string[], opts: Opts): string[] {
  return (
    commonProcessing(files, opts)
      .filter(appDirectoryRoutable)
      .map((file) =>
        // transform filepath to url path
        file
          .split("/")
          // remove named groups
          .filter(
            (segment) => !(segment.startsWith("(") && segment.endsWith(")")),
          )
          // remove page + route from path
          .filter(
            (segment) =>
              !APP_DIRECTORY_ROUTABLE_DIRECTORIES.includes(parse(segment).name),
          )
          // remove slots
          .filter((segment) => !segment.startsWith("@"))
          .join("/"),
      )
      // handle index page
      .map((file) => (file === "" ? "/" : file))
  );
}

const NEXTJS_NON_ROUTABLE = ["/_app", "/_document", "/_error", "/middleware"];

export function getPageRoutes(files: string[], opts: Opts): string[] {
  return (
    commonProcessing(files, opts)
      // remove index if present (/foos/index.ts is the same as /foos.ts)
      .map((file) => file.replace(/index$/, ""))
      // remove trailing slash if present
      .map((file) =>
        file.endsWith("/") && file.length > 2 ? file.slice(0, -1) : file,
      )
      // exclude nextjs special routes
      .filter((file) => !NEXTJS_NON_ROUTABLE.includes(file))
  );
}

export function writeNextJSRoutes(options: NextJSRoutesOptions): void {
  const defaultOptions = {
    usingPagesDirectory: false,
    usingAppDirectory: false,
    dir: process.cwd(),
    outDir: join(options.dir ?? process.cwd(), "@types"),
    pageExtensions: ["tsx", "ts", "jsx", "js"],
  };
  const opts = {
    ...defaultOptions,
    ...options,
  };
  const files = [];
  const pagesDirectory = getPagesDirectory(opts.dir);
  if (pagesDirectory) {
    const routes = getPageRoutes(findFiles(pagesDirectory), {
      pageExtensions: opts.pageExtensions,
      directory: pagesDirectory,
    });
    files.push(...routes);
    opts.usingPagesDirectory = true;
  }
  const appDirectory = getAppDirectory(opts.dir);
  if (appDirectory) {
    const routes = getAppRoutes(findFiles(appDirectory), {
      pageExtensions: opts.pageExtensions,
      directory: appDirectory,
    });
    files.push(...routes);
    opts.usingAppDirectory = true;
  }
  const outputFilepath = join(opts.outDir, "nextjs-routes.d.ts");
  if (opts.outDir && !existsSync(opts.outDir)) {
    mkdirSync(opts.outDir, { recursive: true });
  }
  const routes = nextRoutes(files);
  const generated = generate(routes, opts);
  writeFileSync(outputFilepath, generated);
}
