// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.'
// Run `yarn nextjs-routes` to regenerate this file.

type Routes =
  | { pathname: "/api/hello" }
  | "/api/hello"
  | { pathname: "/bars/[bar]"; query: { bar: string } }
  | { pathname: "/foos/[foo]"; query: { foo: string } }
  | { pathname: "/" }
  | "/";

declare module "next/link" {
  import type { LinkProps as NextLinkProps } from "next/link";
  import type { PropsWithChildren, MouseEventHandler } from "react";

  interface LinkProps extends Omit<NextLinkProps, "href"> {
    href: Routes;
  }

  declare function Link(
    props: PropsWithChildren<LinkProps>
  ): DetailedReactHTMLElement<
    {
      onMouseEnter?: MouseEventHandler<Element> | undefined;
      onClick: MouseEventHandler;
      href?: string | undefined;
      ref?: any;
    },
    HTMLElement
  >;

  export default Link;
}

declare module "next/router" {
  import type { NextRouter } from "next/router";

  type TransitionOptions = Parameters<NextRouter["push"]>[2];

  interface Router extends Omit<NextRouter, "push" | "replace"> {
    push(
      url: Routes,
      as?: Routes,
      options?: TransitionOptions
    ): Promise<boolean>;
    replace(
      url: Routes,
      as?: Routes,
      options?: TransitionOptions
    ): Promise<boolean>;
  }

  export function useRouter(): Router;
}
