// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.'
// Run `yarn nextjs-routes` to regenerate this file.

type Route =
  | { pathname: "/api/hello" }
  | "/api/hello"
  | { pathname: "/bars/[bar]"; query: { bar: string } }
  | { pathname: "/foos/[foo]"; query: { foo: string } }
  | { pathname: "/" }
  | "/";

declare module "nextjs-routes/link" {
  import type { LinkProps as NextLinkProps } from "next/link";
  import type { PropsWithChildren, MouseEventHandler } from "react";

  export interface LinkProps extends Omit<NextLinkProps, "href"> {
    href: Route;
  }

  declare function Link(
    props: PropsWithChildren<LinkProps>
  ): DetailedReactHTMLElement<
    {
      onMouseEnter?: MouseEventHandler<Element> | undefined;
      onClick: MouseEventHandler;
      href?: string | undefined;
      ref?: any;
    },
    HTMLElement
  >;

  export default Link;
}

declare module "nextjs-routes/router" {
  import type { NextRouter as Router } from "next/router";
  export { RouterEvent } from "next/router";

  type TransitionOptions = Parameters<Router["push"]>[2];

  export interface NextRouter extends Omit<Router, "push" | "replace"> {
    push(
      url: Route,
      as?: string,
      options?: TransitionOptions
    ): Promise<boolean>;
    replace(
      url: Route,
      as?: string,
      options?: TransitionOptions
    ): Promise<boolean>;
  }

  export function useRouter(): NextRouter;
}
