import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link href={{ pathname: "/" }}>Home</Link>
        {router.locale === "en-US" ? (
          <button
            onClick={() =>
              router.push({ query: router.query }, undefined, { locale: "fr" })
            }
          >
            French
          </button>
        ) : (
          <button
            onClick={() =>
              router.push({ query: router.query }, undefined, {
                locale: "en-US",
              })
            }
          >
            English
          </button>
        )}
      </main>
    </>
  );
};

export default Home;
