// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.'
// Run `yarn nextjs-routes` to regenerate this file.

//import type { NextUrl } from "nextjs-routes";
// , Router, LinkProps, NextLink
type Routes = NextUrl<"/api/hello"> | NextUrl<"/index">;

declare module "next/link" {
  function Link(props: string): number;
  export default Link;
}

declare module "next/router" {
  export function useRouter(): Router<Routes>;
}
