import type { NextPage } from "next";
import Head from "next/head";
import Link from "nextjs-routes/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link href={{ pathname: "/foos/[foo]", query: { foo: "Foo" } }}>
          Foo
        </Link>
      </main>
    </>
  );
};

export default Home;
