export interface NextUrl<Pathname extends string, Query = Record<string, never>>
  extends URL {
  pathname: Pathname;
  query: Query;
}

/**
 * This type exists as an extension point for the routes autogenerated by `nextjs-routes`. The autogenerated file overrides the `generatedRoutes` field.
 */
interface NextjsRoutes {
  generatedRoutes: never;
}

export type Routes = NextjsRoutes["generatedRoutes"];
