name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  ci:
    name: "Lint and Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm package:build
      - run: pnpm lint
      - run: pnpm test:ci && pnpm codecov --token=$CODECOV_TOKEN
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
