name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-package:
    name: Build Package
    runs-on: ubuntu-latest
    outputs:
      package: ${{ steps.publish-local-package.outputs.package }}
    steps:
      - uses: tatethurston/github-actions/publish-local-package@main
        id: publish-local-package
        with:
          path: packages/nextjs-routes/dist
  ci:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: tatethurston/github-actions/test@main
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
      - uses: tatethurston/github-actions/check-generated-files@main
        with:
          cmd: pnpm examples:regen
  ci-windows:
    name: Windows CI
    runs-on: windows-latest
    needs: build-package
    steps:
      - uses: tatethurston/github-actions/install-local-package@main
        with:
          name: ${{ needs.build-package.outputs.package }}
      - name: Bin Check
        run: |
          echo 'module.exports = {}' > next.config.js
          mkdir pages
          npx --no nextjs-routes
