name: Publish NPM Package
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: tatethurston/github-actions/publish@main
        with:
          package_directory: packages/nextjs-routes/dist
          npm_token: ${{ secrets.NPM_TOKEN }}
